#!/bin/bash

. "${OPENSHIFT_REPO_DIR}.openshift/config.example"

cd $OPENSHIFT_DATA_DIR

# Install Vert.x if needed

if [[ -d vert.x-${VERTX_VERSION} ]]; then
	echo "Vert.x ${VERTX_VERSION} already installed."
else
	for version in vert.x-*; do 
		echo "Removing $version"
		rm -rf $version 
	done

	echo "Installing Vert.x $VERTX_VERSION"

  echo " Downloading http://vertx.io/downloads/vert.x-${VERTX_VERSION}.tar.gz"
	curl --insecure -o vert.x-${VERTX_VERSION}.tar.gz "http://vertx.io/downloads/vert.x-${VERTX_VERSION}.tar.gz"
	tar -xf vert.x-${VERTX_VERSION}.tar.gz
	rm vert.x-${VERTX_VERSION}.tar.gz
fi

# Install JRuby if needed - you can comment this out if you don't use Ruby

if [[ -d jruby-${JRUBY_VERSION} ]]; then
	echo "JRuby ${JRUBY_VERSION} already installed."
else
	for version in jruby-*; do
		echo "Removing $version"
		rm -rf $version
	done

	echo "Installing JRuby $JRUBY_VERSION"

  echo " Downloading http://jruby.org.s3.amazonaws.com/downloads/${JRUBY_VERSION}/jruby-bin-${JRUBY_VERSION}.tar.gz"
	curl --insecure -o jruby-${JRUBY_VERSION}.tar.gz "http://jruby.org.s3.amazonaws.com/downloads/${JRUBY_VERSION}/jruby-bin-${JRUBY_VERSION}.tar.gz"
	tar -xf jruby-${JRUBY_VERSION}.tar.gz
	rm jruby-${JRUBY_VERSION}.tar.gz
fi

# Install Jython if needed - you can comment this out if you don't use Python

if [[ -d jruby-${JRUBY_VERSION} ]]; then
	echo "JRuby ${JRUBY_VERSION} already installed."
else
	for version in jruby-*; do
		echo "Removing $version"
		rm -rf $version
	done

	echo "Installing JRuby $JRUBY_VERSION"

  echo " Downloading http://jruby.org.s3.amazonaws.com/downloads/${JRUBY_VERSION}/jruby-bin-${JRUBY_VERSION}.tar.gz"
	curl --insecure -o jruby-${JRUBY_VERSION}.tar.gz "http://jruby.org.s3.amazonaws.com/downloads/${JRUBY_VERSION}/jruby-bin-${JRUBY_VERSION}.tar.gz"
	tar -xf jruby-${JRUBY_VERSION}.tar.gz
	rm jruby-${JRUBY_VERSION}.tar.gz
fi




