#!/bin/bash

cd $OPENSHIFT_REPO_DIR

. ".openshift/config"

if [[ -e Gemfile ]]; then
	ahash=`sha1sum Gemfile`
	if [[ -e "${OPENSHIFT_DATA_DIR}Gemfile.hsh" ]]; then
		ohash=`cat ${OPENSHIFT_DATA_DIR}Gemfile.hsh`
	else
		ohash=''
	fi

	if [[ "$ahash" == "$ohash" ]]; then
		echo "No change in Gemfile"
	else
		jruby -S bundle install
		echo "$ahash" > ${OPENSHIFT_DATA_DIR}Gemfile.hsh
	fi
fi

echo "Starting Vert.x application!"

if [[ -e $SERVER_FILE ]]; then
	nohup bash -c "exec 'vertx' 'run' '${SERVER_FILE}' &> ${OPENSHIFT_LOG_DIR}vert.x.log" &> /dev/null &
	echo $! > .openshift/application.pid
else
	echo "Server file does not exists."
fi
